
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ElementsBackToTop': typeof import("../components/elements/BackToTop.vue")['default']
    'ElementsCounterUp': typeof import("../components/elements/CounterUp.vue")['default']
    'ElementsModalVideo': typeof import("../components/elements/ModalVideo.vue")['default']
    'LayoutFooter1': typeof import("../components/layout/Footer1.vue")['default']
    'LayoutFooter2': typeof import("../components/layout/Footer2.vue")['default']
    'LayoutHeader1': typeof import("../components/layout/Header1.vue")['default']
    'LayoutHeader2': typeof import("../components/layout/Header2.vue")['default']
    'LayoutMenu': typeof import("../components/layout/Menu.vue")['default']
    'LayoutMobileMenu': typeof import("../components/layout/MobileMenu.vue")['default']
    'LayoutPageTitle': typeof import("../components/layout/PageTitle.vue")['default']
    'SectionsHome1About': typeof import("../components/sections/home1/About.vue")['default']
    'SectionsHome1CallToAction': typeof import("../components/sections/home1/CallToAction.vue")['default']
    'SectionsHome1Clients': typeof import("../components/sections/home1/Clients.vue")['default']
    'SectionsHome1Faq': typeof import("../components/sections/home1/Faq.vue")['default']
    'SectionsHome1FormVideo': typeof import("../components/sections/home1/FormVideo.vue")['default']
    'SectionsHome1Funfact': typeof import("../components/sections/home1/Funfact.vue")['default']
    'SectionsHome1News': typeof import("../components/sections/home1/News.vue")['default']
    'SectionsHome1Projects': typeof import("../components/sections/home1/Projects.vue")['default']
    'SectionsHome1Services': typeof import("../components/sections/home1/Services.vue")['default']
    'SectionsHome1Slider': typeof import("../components/sections/home1/Slider.vue")['default']
    'SectionsHome1Testimonial': typeof import("../components/sections/home1/Testimonial.vue")['default']
    'SectionsHome1Testimonial2': typeof import("../components/sections/home1/Testimonial2.vue")['default']
    'SectionsHome1Work': typeof import("../components/sections/home1/Work.vue")['default']
    'SectionsHome2About': typeof import("../components/sections/home2/About.vue")['default']
    'SectionsHome2Banner': typeof import("../components/sections/home2/Banner.vue")['default']
    'SectionsHome2CallToAction': typeof import("../components/sections/home2/CallToAction.vue")['default']
    'SectionsHome2Clients': typeof import("../components/sections/home2/Clients.vue")['default']
    'SectionsHome2FormMap': typeof import("../components/sections/home2/FormMap.vue")['default']
    'SectionsHome2News': typeof import("../components/sections/home2/News.vue")['default']
    'SectionsHome2Pricing': typeof import("../components/sections/home2/Pricing.vue")['default']
    'SectionsHome2Services': typeof import("../components/sections/home2/Services.vue")['default']
    'SectionsHome2Team': typeof import("../components/sections/home2/Team.vue")['default']
    'SectionsHome2Testimonial': typeof import("../components/sections/home2/Testimonial.vue")['default']
    'SectionsInnerpagesAbout': typeof import("../components/sections/innerpages/About.vue")['default']
    'SectionsInnerpagesAbout2': typeof import("../components/sections/innerpages/About2.vue")['default']
    'SectionsInnerpagesAbout3': typeof import("../components/sections/innerpages/About3.vue")['default']
    'SectionsInnerpagesAbout4': typeof import("../components/sections/innerpages/About4.vue")['default']
    'SectionsInnerpagesContact': typeof import("../components/sections/innerpages/Contact.vue")['default']
    'SectionsInnerpagesError': typeof import("../components/sections/innerpages/Error.vue")['default']
    'SectionsInnerpagesFaq': typeof import("../components/sections/innerpages/Faq.vue")['default']
    'SectionsInnerpagesNewsDetails': typeof import("../components/sections/innerpages/NewsDetails.vue")['default']
    'SectionsInnerpagesNewsGrid': typeof import("../components/sections/innerpages/NewsGrid.vue")['default']
    'SectionsInnerpagesPricing': typeof import("../components/sections/innerpages/Pricing.vue")['default']
    'SectionsInnerpagesProjectDetails': typeof import("../components/sections/innerpages/ProjectDetails.vue")['default']
    'SectionsInnerpagesProjectGrid': typeof import("../components/sections/innerpages/ProjectGrid.vue")['default']
    'SectionsInnerpagesServiceDetails': typeof import("../components/sections/innerpages/ServiceDetails.vue")['default']
    'SectionsInnerpagesServiceGrid': typeof import("../components/sections/innerpages/ServiceGrid.vue")['default']
    'SectionsInnerpagesTeamDetails': typeof import("../components/sections/innerpages/TeamDetails.vue")['default']
    'SectionsInnerpagesTeamGrid': typeof import("../components/sections/innerpages/TeamGrid.vue")['default']
    'SectionsInnerpagesTestimonial': typeof import("../components/sections/innerpages/Testimonial.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyElementsBackToTop': typeof import("../components/elements/BackToTop.vue")['default']
    'LazyElementsCounterUp': typeof import("../components/elements/CounterUp.vue")['default']
    'LazyElementsModalVideo': typeof import("../components/elements/ModalVideo.vue")['default']
    'LazyLayoutFooter1': typeof import("../components/layout/Footer1.vue")['default']
    'LazyLayoutFooter2': typeof import("../components/layout/Footer2.vue")['default']
    'LazyLayoutHeader1': typeof import("../components/layout/Header1.vue")['default']
    'LazyLayoutHeader2': typeof import("../components/layout/Header2.vue")['default']
    'LazyLayoutMenu': typeof import("../components/layout/Menu.vue")['default']
    'LazyLayoutMobileMenu': typeof import("../components/layout/MobileMenu.vue")['default']
    'LazyLayoutPageTitle': typeof import("../components/layout/PageTitle.vue")['default']
    'LazySectionsHome1About': typeof import("../components/sections/home1/About.vue")['default']
    'LazySectionsHome1CallToAction': typeof import("../components/sections/home1/CallToAction.vue")['default']
    'LazySectionsHome1Clients': typeof import("../components/sections/home1/Clients.vue")['default']
    'LazySectionsHome1Faq': typeof import("../components/sections/home1/Faq.vue")['default']
    'LazySectionsHome1FormVideo': typeof import("../components/sections/home1/FormVideo.vue")['default']
    'LazySectionsHome1Funfact': typeof import("../components/sections/home1/Funfact.vue")['default']
    'LazySectionsHome1News': typeof import("../components/sections/home1/News.vue")['default']
    'LazySectionsHome1Projects': typeof import("../components/sections/home1/Projects.vue")['default']
    'LazySectionsHome1Services': typeof import("../components/sections/home1/Services.vue")['default']
    'LazySectionsHome1Slider': typeof import("../components/sections/home1/Slider.vue")['default']
    'LazySectionsHome1Testimonial': typeof import("../components/sections/home1/Testimonial.vue")['default']
    'LazySectionsHome1Testimonial2': typeof import("../components/sections/home1/Testimonial2.vue")['default']
    'LazySectionsHome1Work': typeof import("../components/sections/home1/Work.vue")['default']
    'LazySectionsHome2About': typeof import("../components/sections/home2/About.vue")['default']
    'LazySectionsHome2Banner': typeof import("../components/sections/home2/Banner.vue")['default']
    'LazySectionsHome2CallToAction': typeof import("../components/sections/home2/CallToAction.vue")['default']
    'LazySectionsHome2Clients': typeof import("../components/sections/home2/Clients.vue")['default']
    'LazySectionsHome2FormMap': typeof import("../components/sections/home2/FormMap.vue")['default']
    'LazySectionsHome2News': typeof import("../components/sections/home2/News.vue")['default']
    'LazySectionsHome2Pricing': typeof import("../components/sections/home2/Pricing.vue")['default']
    'LazySectionsHome2Services': typeof import("../components/sections/home2/Services.vue")['default']
    'LazySectionsHome2Team': typeof import("../components/sections/home2/Team.vue")['default']
    'LazySectionsHome2Testimonial': typeof import("../components/sections/home2/Testimonial.vue")['default']
    'LazySectionsInnerpagesAbout': typeof import("../components/sections/innerpages/About.vue")['default']
    'LazySectionsInnerpagesAbout2': typeof import("../components/sections/innerpages/About2.vue")['default']
    'LazySectionsInnerpagesAbout3': typeof import("../components/sections/innerpages/About3.vue")['default']
    'LazySectionsInnerpagesAbout4': typeof import("../components/sections/innerpages/About4.vue")['default']
    'LazySectionsInnerpagesContact': typeof import("../components/sections/innerpages/Contact.vue")['default']
    'LazySectionsInnerpagesError': typeof import("../components/sections/innerpages/Error.vue")['default']
    'LazySectionsInnerpagesFaq': typeof import("../components/sections/innerpages/Faq.vue")['default']
    'LazySectionsInnerpagesNewsDetails': typeof import("../components/sections/innerpages/NewsDetails.vue")['default']
    'LazySectionsInnerpagesNewsGrid': typeof import("../components/sections/innerpages/NewsGrid.vue")['default']
    'LazySectionsInnerpagesPricing': typeof import("../components/sections/innerpages/Pricing.vue")['default']
    'LazySectionsInnerpagesProjectDetails': typeof import("../components/sections/innerpages/ProjectDetails.vue")['default']
    'LazySectionsInnerpagesProjectGrid': typeof import("../components/sections/innerpages/ProjectGrid.vue")['default']
    'LazySectionsInnerpagesServiceDetails': typeof import("../components/sections/innerpages/ServiceDetails.vue")['default']
    'LazySectionsInnerpagesServiceGrid': typeof import("../components/sections/innerpages/ServiceGrid.vue")['default']
    'LazySectionsInnerpagesTeamDetails': typeof import("../components/sections/innerpages/TeamDetails.vue")['default']
    'LazySectionsInnerpagesTeamGrid': typeof import("../components/sections/innerpages/TeamGrid.vue")['default']
    'LazySectionsInnerpagesTestimonial': typeof import("../components/sections/innerpages/Testimonial.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ElementsBackToTop: typeof import("../components/elements/BackToTop.vue")['default']
export const ElementsCounterUp: typeof import("../components/elements/CounterUp.vue")['default']
export const ElementsModalVideo: typeof import("../components/elements/ModalVideo.vue")['default']
export const LayoutFooter1: typeof import("../components/layout/Footer1.vue")['default']
export const LayoutFooter2: typeof import("../components/layout/Footer2.vue")['default']
export const LayoutHeader1: typeof import("../components/layout/Header1.vue")['default']
export const LayoutHeader2: typeof import("../components/layout/Header2.vue")['default']
export const LayoutMenu: typeof import("../components/layout/Menu.vue")['default']
export const LayoutMobileMenu: typeof import("../components/layout/MobileMenu.vue")['default']
export const LayoutPageTitle: typeof import("../components/layout/PageTitle.vue")['default']
export const SectionsHome1About: typeof import("../components/sections/home1/About.vue")['default']
export const SectionsHome1CallToAction: typeof import("../components/sections/home1/CallToAction.vue")['default']
export const SectionsHome1Clients: typeof import("../components/sections/home1/Clients.vue")['default']
export const SectionsHome1Faq: typeof import("../components/sections/home1/Faq.vue")['default']
export const SectionsHome1FormVideo: typeof import("../components/sections/home1/FormVideo.vue")['default']
export const SectionsHome1Funfact: typeof import("../components/sections/home1/Funfact.vue")['default']
export const SectionsHome1News: typeof import("../components/sections/home1/News.vue")['default']
export const SectionsHome1Projects: typeof import("../components/sections/home1/Projects.vue")['default']
export const SectionsHome1Services: typeof import("../components/sections/home1/Services.vue")['default']
export const SectionsHome1Slider: typeof import("../components/sections/home1/Slider.vue")['default']
export const SectionsHome1Testimonial: typeof import("../components/sections/home1/Testimonial.vue")['default']
export const SectionsHome1Testimonial2: typeof import("../components/sections/home1/Testimonial2.vue")['default']
export const SectionsHome1Work: typeof import("../components/sections/home1/Work.vue")['default']
export const SectionsHome2About: typeof import("../components/sections/home2/About.vue")['default']
export const SectionsHome2Banner: typeof import("../components/sections/home2/Banner.vue")['default']
export const SectionsHome2CallToAction: typeof import("../components/sections/home2/CallToAction.vue")['default']
export const SectionsHome2Clients: typeof import("../components/sections/home2/Clients.vue")['default']
export const SectionsHome2FormMap: typeof import("../components/sections/home2/FormMap.vue")['default']
export const SectionsHome2News: typeof import("../components/sections/home2/News.vue")['default']
export const SectionsHome2Pricing: typeof import("../components/sections/home2/Pricing.vue")['default']
export const SectionsHome2Services: typeof import("../components/sections/home2/Services.vue")['default']
export const SectionsHome2Team: typeof import("../components/sections/home2/Team.vue")['default']
export const SectionsHome2Testimonial: typeof import("../components/sections/home2/Testimonial.vue")['default']
export const SectionsInnerpagesAbout: typeof import("../components/sections/innerpages/About.vue")['default']
export const SectionsInnerpagesAbout2: typeof import("../components/sections/innerpages/About2.vue")['default']
export const SectionsInnerpagesAbout3: typeof import("../components/sections/innerpages/About3.vue")['default']
export const SectionsInnerpagesAbout4: typeof import("../components/sections/innerpages/About4.vue")['default']
export const SectionsInnerpagesContact: typeof import("../components/sections/innerpages/Contact.vue")['default']
export const SectionsInnerpagesError: typeof import("../components/sections/innerpages/Error.vue")['default']
export const SectionsInnerpagesFaq: typeof import("../components/sections/innerpages/Faq.vue")['default']
export const SectionsInnerpagesNewsDetails: typeof import("../components/sections/innerpages/NewsDetails.vue")['default']
export const SectionsInnerpagesNewsGrid: typeof import("../components/sections/innerpages/NewsGrid.vue")['default']
export const SectionsInnerpagesPricing: typeof import("../components/sections/innerpages/Pricing.vue")['default']
export const SectionsInnerpagesProjectDetails: typeof import("../components/sections/innerpages/ProjectDetails.vue")['default']
export const SectionsInnerpagesProjectGrid: typeof import("../components/sections/innerpages/ProjectGrid.vue")['default']
export const SectionsInnerpagesServiceDetails: typeof import("../components/sections/innerpages/ServiceDetails.vue")['default']
export const SectionsInnerpagesServiceGrid: typeof import("../components/sections/innerpages/ServiceGrid.vue")['default']
export const SectionsInnerpagesTeamDetails: typeof import("../components/sections/innerpages/TeamDetails.vue")['default']
export const SectionsInnerpagesTeamGrid: typeof import("../components/sections/innerpages/TeamGrid.vue")['default']
export const SectionsInnerpagesTestimonial: typeof import("../components/sections/innerpages/Testimonial.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyElementsBackToTop: typeof import("../components/elements/BackToTop.vue")['default']
export const LazyElementsCounterUp: typeof import("../components/elements/CounterUp.vue")['default']
export const LazyElementsModalVideo: typeof import("../components/elements/ModalVideo.vue")['default']
export const LazyLayoutFooter1: typeof import("../components/layout/Footer1.vue")['default']
export const LazyLayoutFooter2: typeof import("../components/layout/Footer2.vue")['default']
export const LazyLayoutHeader1: typeof import("../components/layout/Header1.vue")['default']
export const LazyLayoutHeader2: typeof import("../components/layout/Header2.vue")['default']
export const LazyLayoutMenu: typeof import("../components/layout/Menu.vue")['default']
export const LazyLayoutMobileMenu: typeof import("../components/layout/MobileMenu.vue")['default']
export const LazyLayoutPageTitle: typeof import("../components/layout/PageTitle.vue")['default']
export const LazySectionsHome1About: typeof import("../components/sections/home1/About.vue")['default']
export const LazySectionsHome1CallToAction: typeof import("../components/sections/home1/CallToAction.vue")['default']
export const LazySectionsHome1Clients: typeof import("../components/sections/home1/Clients.vue")['default']
export const LazySectionsHome1Faq: typeof import("../components/sections/home1/Faq.vue")['default']
export const LazySectionsHome1FormVideo: typeof import("../components/sections/home1/FormVideo.vue")['default']
export const LazySectionsHome1Funfact: typeof import("../components/sections/home1/Funfact.vue")['default']
export const LazySectionsHome1News: typeof import("../components/sections/home1/News.vue")['default']
export const LazySectionsHome1Projects: typeof import("../components/sections/home1/Projects.vue")['default']
export const LazySectionsHome1Services: typeof import("../components/sections/home1/Services.vue")['default']
export const LazySectionsHome1Slider: typeof import("../components/sections/home1/Slider.vue")['default']
export const LazySectionsHome1Testimonial: typeof import("../components/sections/home1/Testimonial.vue")['default']
export const LazySectionsHome1Testimonial2: typeof import("../components/sections/home1/Testimonial2.vue")['default']
export const LazySectionsHome1Work: typeof import("../components/sections/home1/Work.vue")['default']
export const LazySectionsHome2About: typeof import("../components/sections/home2/About.vue")['default']
export const LazySectionsHome2Banner: typeof import("../components/sections/home2/Banner.vue")['default']
export const LazySectionsHome2CallToAction: typeof import("../components/sections/home2/CallToAction.vue")['default']
export const LazySectionsHome2Clients: typeof import("../components/sections/home2/Clients.vue")['default']
export const LazySectionsHome2FormMap: typeof import("../components/sections/home2/FormMap.vue")['default']
export const LazySectionsHome2News: typeof import("../components/sections/home2/News.vue")['default']
export const LazySectionsHome2Pricing: typeof import("../components/sections/home2/Pricing.vue")['default']
export const LazySectionsHome2Services: typeof import("../components/sections/home2/Services.vue")['default']
export const LazySectionsHome2Team: typeof import("../components/sections/home2/Team.vue")['default']
export const LazySectionsHome2Testimonial: typeof import("../components/sections/home2/Testimonial.vue")['default']
export const LazySectionsInnerpagesAbout: typeof import("../components/sections/innerpages/About.vue")['default']
export const LazySectionsInnerpagesAbout2: typeof import("../components/sections/innerpages/About2.vue")['default']
export const LazySectionsInnerpagesAbout3: typeof import("../components/sections/innerpages/About3.vue")['default']
export const LazySectionsInnerpagesAbout4: typeof import("../components/sections/innerpages/About4.vue")['default']
export const LazySectionsInnerpagesContact: typeof import("../components/sections/innerpages/Contact.vue")['default']
export const LazySectionsInnerpagesError: typeof import("../components/sections/innerpages/Error.vue")['default']
export const LazySectionsInnerpagesFaq: typeof import("../components/sections/innerpages/Faq.vue")['default']
export const LazySectionsInnerpagesNewsDetails: typeof import("../components/sections/innerpages/NewsDetails.vue")['default']
export const LazySectionsInnerpagesNewsGrid: typeof import("../components/sections/innerpages/NewsGrid.vue")['default']
export const LazySectionsInnerpagesPricing: typeof import("../components/sections/innerpages/Pricing.vue")['default']
export const LazySectionsInnerpagesProjectDetails: typeof import("../components/sections/innerpages/ProjectDetails.vue")['default']
export const LazySectionsInnerpagesProjectGrid: typeof import("../components/sections/innerpages/ProjectGrid.vue")['default']
export const LazySectionsInnerpagesServiceDetails: typeof import("../components/sections/innerpages/ServiceDetails.vue")['default']
export const LazySectionsInnerpagesServiceGrid: typeof import("../components/sections/innerpages/ServiceGrid.vue")['default']
export const LazySectionsInnerpagesTeamDetails: typeof import("../components/sections/innerpages/TeamDetails.vue")['default']
export const LazySectionsInnerpagesTeamGrid: typeof import("../components/sections/innerpages/TeamGrid.vue")['default']
export const LazySectionsInnerpagesTestimonial: typeof import("../components/sections/innerpages/Testimonial.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
